### ISSUE TITLE
学硕选修工程伦理的问题

### ISSUE THREAD

**Issue by Ming-Yang** [yaowenxu/BUAA1806S7-ISSUES#7]
学硕如果选修工程伦理，还用选其他人文或管理专题课吗

**Comment by yaowenxu** [comment]
回复：通知只是说工程硕士（专硕）选了工程伦理就不用选人文or管理课，既然没有提及学硕，那么学硕就该按自己的培养方案选人文or管理课，注意选课时间， http://graduate.buaa.edu.cn/ch/tongzhi/5505.jhtml

**Comment by Ming-Yang** [comment]
![default](https://user-images.githubusercontent.com/22511910/45527393-e8864780-b80d-11e8-8389-fed91a80cdb0.png)
在选课单上，【工程伦理】在【人文和管理专题课】【专题课大类】下，而其他的【人文和管理专题课】都选没了，所以想问学硕可以把【工程伦理】当作【人文和管理专题课】吗

**Comment by Ming-Yang** [comment]
> 
> 
> 回复：通知只是说工程硕士（专硕）选了工程伦理就不用选人文or管理课，既然没有提及学硕，那么学硕就该按自己的培养方案选人文or管理课，注意选课时间， http://graduate.buaa.edu.cn/ch/tongzhi/5505.jhtml

![default](https://user-images.githubusercontent.com/22511910/45527393-e8864780-b80d-11e8-8389-fed91a80cdb0.png)
在选课单上，【工程伦理】在【人文和管理专题课】【专题课大类】下，而其他的【人文和管理专题课】都时间不合适，所以想问学硕可以把【工程伦理】当作【人文和管理专题课】吗

**Comment by yaowenxu** [comment]
王导：@7_xxx_班长 你那个问题，谭老师说不可以， 如果有问题请打电话咨询谭老师，电话发你wechat 了。
